[package]
name = "cyancia_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
cyancia_canvas.workspace = true
cyancia_input.workspace = true
cyancia_id.workspace = true
iced_core.workspace = true
cyancia_actions.workspace = true
